#' Print install messages for datasets
#'
#' Displays informative messages about which datasets will be installed,
#' which are missing, which are outdated, and which will not be installed
#' The messages are based on the `comment` column of the provided instructions
#' data frame.
#'
#' @param instructions data.frame. A dataset of installation instructions,
#'   generated by `.get_installation_instructions()`. Must contain at least the columns
#'   `name` and `comment`.
#'
#' @return Invisibly returns `NULL`.
#'
#' @keywords internal
#' @noRd
.generate_installation_messages <- function(instructions) {

  categories <- c(
    "always"       = "will be installed",
    "missing"      = "are missing and will be installed",
    "outdated"     = "are outdated and will be installed",
    "not missing"  = "are already present and will not be installed",
    "not outdated" = "are up-to-date and will not be installed"
  )

  for (cat in names(categories)) {

    names_to_show <- instructions$name[instructions$comment == cat]

    if (!length(names_to_show)) next

    cli::cli_text(paste0("The following datasets ", categories[cat], ":"))
    cli::cli_bullets(.names_to_bullet_list(names_to_show))
  }

  invisible(NULL)
}

